// tests/smoke-settings.test.ts
//
// BUG-189 regression: demo/run-smoke.sh renders the smoke workers'
// .claude/settings.json. When the checkout path contains a double quote or
// backslash, the old shell heredoc produced invalid JSON (or a mangled hook
// command) and the paid smoke workers started without the Fleet hooks. The
// settings must be generated by a real serializer and the hook commands must
// still shell-resolve to the exact script paths.

import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const RENDERER = path.join(REPO_ROOT, 'demo', 'render-smoke-settings.mjs');

interface HookCommand {
  command: string;
  timeout?: number;
  async?: boolean;
}
interface HookGroup {
  matcher?: string;
  hooks: HookCommand[];
}
interface SmokeSettings {
  hooks: Record<string, HookGroup[]>;
}

function firstGroup(groups: HookGroup[] | undefined, label: string): HookGroup {
  const group = groups?.[0];
  assert.ok(group, `${label}: missing hook group`);
  return group;
}
function firstCommand(groups: HookGroup[] | undefined, label: string): HookCommand {
  const hook = firstGroup(groups, label).hooks[0];
  assert.ok(hook, `${label}: missing hook command`);
  return hook;
}

// Paths exercising the bug's trigger characters: double quote, backslash,
// dollar/backtick (shell expansion inside the old heredoc) and a single quote.
const HOSTILE_SESSIONSTART = '/tmp/checkout "quoted"/scripts/fleet-sessionstart.mjs';
const HOSTILE_HOOK = "/tmp/checkout dir\\with\\backslashes/`evil`$(x)/it's/scripts/fleet-hook.mjs";

function render(sessionStart: string, hook: string) {
  const dir = mkdtempSync(path.join(tmpdir(), 'fleetdeck-smoke-settings-'));
  const out = path.join(dir, 'settings.json');
  execFileSync(process.execPath, [RENDERER, sessionStart, hook, out]);
  return { dir, raw: readFileSync(out, 'utf8') };
}

test('smoke settings.json stays valid JSON with quotes and backslashes in the checkout path', (t) => {
  const { dir, raw } = render(HOSTILE_SESSIONSTART, HOSTILE_HOOK);
  t.after(() => {
    rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
  });

  const settings = JSON.parse(raw) as SmokeSettings; // throws when the heredoc-corrupted shape returns

  const sessionStartCommand = firstCommand(settings.hooks['SessionStart'], 'SessionStart').command;
  const stopCommand = firstCommand(settings.hooks['Stop'], 'Stop').command;

  // The shell-parse of each command must recover the exact script path — a
  // literal "node \"$PATH\"" embedding would leave the quote/backslash
  // characters to break either the JSON or the shell command.
  const shWord = (command: string) =>
    execFileSync('bash', ['-c', `set -- ${command}; printf '%s' "$2"`], { encoding: 'utf8' });
  assert.equal(shWord(sessionStartCommand), HOSTILE_SESSIONSTART);
  assert.equal(shWord(stopCommand), HOSTILE_HOOK);
  assert.match(stopCommand, / Stop$/);
});

test('smoke settings.json preserves the hook table (events, matchers, timeouts)', (t) => {
  const { dir, raw } = render(
    '/repo/scripts/fleet-sessionstart.mjs',
    '/repo/scripts/fleet-hook.mjs',
  );
  t.after(() => {
    rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
  });

  const settings = JSON.parse(raw) as SmokeSettings;
  assert.deepEqual(Object.keys(settings.hooks), [
    'SessionStart',
    'UserPromptSubmit',
    'PostToolUse',
    'PreToolUse',
    'PermissionRequest',
    'Elicitation',
    'Notification',
    'Stop',
    'SessionEnd',
    'FileChanged',
  ]);
  assert.equal(
    firstGroup(settings.hooks['PostToolUse'], 'PostToolUse').matcher,
    'Edit|Write|MultiEdit|NotebookEdit|Bash',
  );
  assert.equal(firstGroup(settings.hooks['PreToolUse'], 'PreToolUse').matcher, 'AskUserQuestion');
  assert.equal(firstCommand(settings.hooks['SessionStart'], 'SessionStart').timeout, 15);
  assert.equal(firstCommand(settings.hooks['PermissionRequest'], 'PermissionRequest').timeout, 65);
  assert.equal(firstCommand(settings.hooks['Notification'], 'Notification').async, true);
  assert.equal(
    firstCommand(settings.hooks['Stop'], 'Stop').command,
    "node '/repo/scripts/fleet-hook.mjs' Stop",
  );
});
