import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const REPO_ROOT = path.resolve(import.meta.dir, '../..');
const DAEMON_BUNDLE = path.join(REPO_ROOT, 'src', 'daemon', 'fleetd.bundle.mjs');
const RAW_BUDGET_BYTES = 750 * 1024;
const GZIP_BUDGET_BYTES = 185 * 1024;

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function packageScripts(): Record<string, unknown> {
  const manifest: unknown = JSON.parse(readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8'));
  expect(isRecord(manifest)).toBe(true);
  const scripts = isRecord(manifest) ? manifest['scripts'] : undefined;
  expect(isRecord(scripts)).toBe(true);
  return isRecord(scripts) ? scripts : {};
}

test('daemon build minifies only local identifiers and preserves diagnostic names and lines', () => {
  const recipe = packageScripts()['bundle'];
  expect(recipe).toBeString();
  expect(recipe).toMatch(/(?:^|\s)--minify-identifiers(?:\s|$)/);
  expect(recipe).toMatch(/(?:^|\s)--keep-names(?:\s|$)/);
  expect(recipe).not.toMatch(/(?:^|\s)--minify(?:\s|$)/);
  expect(recipe).not.toMatch(/(?:^|\s)--minify-whitespace(?:\s|$)/);
});

test('generated daemon preserves root diagnostic names and stays inside the accepted budget', () => {
  const bytes = readFileSync(DAEMON_BUNDLE);
  const source = bytes.toString('utf8');
  const gzip = Bun.gzipSync(bytes, { level: 9, library: 'zlib' });

  expect(source).toStartWith("#!/usr/bin/env bun\n// GENERATED by 'bun run bundle' — do not edit.");
  expect(source.split('\n').length).toBeGreaterThan(10_000);
  expect(source).toContain('"DaemonHostControl"');
  expect(source).toContain('"LifecycleCoordinator"');
  expect(source).toContain('"BunProcessDriver"');
  expect(source).toContain('"makeDaemonApp"');

  expect(bytes.byteLength).toBeLessThanOrEqual(RAW_BUDGET_BYTES);
  expect(gzip.byteLength).toBeLessThanOrEqual(GZIP_BUDGET_BYTES);
});
