#!/usr/bin/env bun
// GENERATED-BY-HAND — P12.1 trial. Programmatic Bun-native build for the five
// generated JS artifacts, mirroring the three esbuild recipes in package.json
// (`bundle`, `bundle:bin`, `bundle:hooks`) via Bun.build({ target: 'bun',
// format: 'esm' }). This is a SELECTION TRIAL only: the committed artifacts stay
// esbuild until the bundler is adjudicated (docs/v1/effect-migration-plan.md
// §P12). It never writes the repo's committed paths unless explicitly pointed at
// the repo root; the trial always passes a scratch outBaseDir.
//
// Usage:
//   bun scripts/bundle-bun.ts <outBaseDir>   # mirror repo layout under outBaseDir
//   bun scripts/bundle-bun.ts                # in-place (repo root) — NOT used by the trial
//
// Parity notes vs esbuild recipes:
//   - Bun preserves the entry shebang but inserts its own `// @bun` fast-path
//     pragma on line 2. We remove that line so the artifact head is exactly
//     `#!/usr/bin/env bun` + the GENERATED banner, matching esbuild and the
//     daemon-bundle-policy `startsWith` contract. (Cost: Bun's pre-bundled cold
//     path is forfeited; measured separately.)
//   - esbuild `--keep-names` has no Bun.build equivalent; the daemon diagnostic
//     names checked by the policy gate are STRING literals and are unaffected.
//   - The daemon post-steps (`@__PURE__` strip, then scripts/strip-bundle-jsdoc.ts)
//     are applied verbatim so the gzip-headroom lever and its self-audit run
//     against the Bun output exactly as they do against esbuild output.

import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const REPO = path.resolve(import.meta.dir, '..');
const outBase = process.argv[2] ? path.resolve(process.argv[2]) : REPO;

const DAEMON_BANNER =
  "// GENERATED by 'bun run bundle' — do not edit. Source: src/daemon/*.ts\n" +
  "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);";
const BIN_BANNER = "// GENERATED by 'bun run bundle:bin' — do not edit. Source: bin/*.ts";
const HOOK_BANNER =
  "// GENERATED by 'bun run bundle:hooks' — do not edit. Source: scripts/fleet-*.ts";

interface Target {
  readonly entry: string; // relative to REPO
  readonly outfile: string; // relative to outBase (mirrors repo layout)
  readonly banner: string;
  readonly minifyIdentifiers: boolean; // daemon only, matches --minify-identifiers --minify-syntax
  readonly daemonPostSteps: boolean; // @__PURE__ strip + strip-bundle-jsdoc
}

const TARGETS: readonly Target[] = [
  {
    entry: 'src/daemon/fleetd.ts',
    outfile: 'src/daemon/fleetd.bundle.mjs',
    banner: DAEMON_BANNER,
    minifyIdentifiers: true,
    daemonPostSteps: true,
  },
  {
    entry: 'bin/fleetdeck.ts',
    outfile: 'bin/fleetdeck.mjs',
    banner: BIN_BANNER,
    minifyIdentifiers: false,
    daemonPostSteps: false,
  },
  {
    entry: 'scripts/fleet-hook.ts',
    outfile: 'scripts/fleet-hook.mjs',
    banner: HOOK_BANNER,
    minifyIdentifiers: false,
    daemonPostSteps: false,
  },
  {
    entry: 'scripts/fleet-sessionstart.ts',
    outfile: 'scripts/fleet-sessionstart.mjs',
    banner: HOOK_BANNER,
    minifyIdentifiers: false,
    daemonPostSteps: false,
  },
  {
    entry: 'scripts/fleet-watch.ts',
    outfile: 'scripts/fleet-watch.mjs',
    banner: HOOK_BANNER,
    minifyIdentifiers: false,
    daemonPostSteps: false,
  },
];

// Bun inserts `// @bun` as the line immediately after the shebang. Drop exactly
// that one line so the head becomes shebang + GENERATED banner (esbuild parity).
function removeBunPragma(code: string): string {
  const lines = code.split('\n');
  for (let i = 0; i < Math.min(3, lines.length); i += 1) {
    if (lines[i] === '// @bun') {
      lines.splice(i, 1);
      return lines.join('\n');
    }
  }
  return code;
}

// The esbuild daemon recipe strips `/* @__PURE__ */` annotations before the
// jsdoc lever. Replicate the exact two split/join passes.
function stripPureAnnotations(code: string): string {
  return code.split('/* @__PURE__ */ ').join('').split('/* @__PURE__ */').join('');
}

async function buildTarget(t: Target): Promise<void> {
  const entryAbs = path.join(REPO, t.entry);
  const outAbs = path.join(outBase, t.outfile);
  const started = Bun.nanoseconds();
  const res = await Bun.build({
    entrypoints: [entryAbs],
    target: 'bun',
    format: 'esm',
    banner: t.banner,
    external: ['bun:sqlite'],
    minify: t.minifyIdentifiers
      ? { identifiers: true, syntax: true, whitespace: false }
      : { identifiers: false, syntax: false, whitespace: false },
  });
  if (!res.success) {
    for (const log of res.logs) process.stderr.write(String(log) + '\n');
    throw new Error(`Bun.build failed for ${t.entry}`);
  }
  if (res.outputs.length !== 1) {
    throw new Error(`Bun.build produced ${res.outputs.length} outputs for ${t.entry}, expected 1`);
  }
  let code = await res.outputs[0]!.text();
  code = removeBunPragma(code);

  mkdirSync(path.dirname(outAbs), { recursive: true });

  if (t.daemonPostSteps) {
    code = stripPureAnnotations(code);
    writeFileSync(outAbs, code);
    // Run the real strip-bundle-jsdoc lever + its self-audit against the Bun
    // output, exactly as `bun run bundle` does against esbuild output. On the
    // esbuild artifact this succeeds; on the Bun artifact its DIAGNOSTIC_NAMES
    // survival check fails because Bun.build has no `--keep-names` equivalent
    // (the quoted diagnostic names are esbuild keep-names injections). Record
    // the divergence but keep the pre-strip Bun daemon as the artifact so the
    // rest of the comparison can still run. Set P12_STRICT=1 to make it fatal.
    const strip = spawnSync(
      process.execPath,
      [path.join(REPO, 'scripts', 'strip-bundle-jsdoc.ts'), outAbs],
      { encoding: 'utf8' },
    );
    process.stdout.write(strip.stdout ?? '');
    if (strip.status !== 0) {
      process.stderr.write(
        `WARN strip-bundle-jsdoc self-audit FAILED on Bun daemon (exit ${strip.status}):\n`,
      );
      process.stderr.write(
        (strip.stderr ?? '')
          .split('\n')
          .filter((l) => l.startsWith('error:'))
          .join('\n') + '\n',
      );
      // Re-write the pre-strip daemon (strip-bundle-jsdoc leaves the file
      // untouched when its audit throws, but be explicit and deterministic).
      writeFileSync(outAbs, code);
      if (process.env['P12_STRICT'] === '1') {
        throw new Error('P12_STRICT: strip-bundle-jsdoc self-audit failed on Bun daemon output');
      }
    }
  } else {
    writeFileSync(outAbs, code);
  }

  const elapsedMs = (Bun.nanoseconds() - started) / 1e6;
  const bytes = Bun.file(outAbs).size;
  process.stdout.write(`built ${t.outfile}  ${bytes} bytes  ${elapsedMs.toFixed(1)}ms\n`);
}

async function main(): Promise<void> {
  process.stdout.write(`Bun.build → ${outBase}\n`);
  for (const t of TARGETS) {
    await buildTarget(t);
  }
  process.stdout.write('done\n');
}

await main();
