#!/usr/bin/env bun
// GENERATED by 'bun run bundle:hooks' — do not edit. Source: scripts/fleet-*.ts

// scripts/fleet-watch.ts
import fs4 from "node:fs";
import path3 from "node:path";
import { randomUUID } from "node:crypto";

// src/daemon/config.ts
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
function resolveHome() {
  const fallbackBase = os.homedir() || "/tmp";
  const configured = process.env["FLEETDECK_HOME"]?.trim();
  if (!configured) return path.join(fallbackBase, ".fleetdeck");
  if (!path.isAbsolute(configured)) return path.resolve(fallbackBase, configured);
  return path.normalize(configured);
}
function resolvePort() {
  const raw2 = process.env["FLEETDECK_PORT"];
  if (raw2 === void 0 || raw2 === "") return 4711;
  const port = Number(raw2);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(
      `invalid FLEETDECK_PORT ${JSON.stringify(raw2)} \u2014 expected an integer port in 1..65535 (port 0 is not supported)`
    );
  }
  return port;
}
function resolveBase(port = resolvePort()) {
  return `http://127.0.0.1:${port}`;
}
function readToken(home) {
  try {
    return fs.readFileSync(path.join(home, "token"), "utf8").trim() || null;
  } catch {
    return null;
  }
}

// scripts/claude-compat.ts
import { execFile, execFileSync } from "node:child_process";
import fs3 from "node:fs";
import path2 from "node:path";

// compatibility.json
var compatibility_default = {
  schema: 1,
  claudeCode: {
    min: "2.1.206",
    max: "2.1.234"
  }
};

// package.json
var package_default = {
  name: "fleetdeck",
  version: "0.23.4",
  description: "Fleet Deck \u2014 localhost daemon + board for Claude Code, guarded by a release-bound compatibility policy.",
  type: "module",
  license: "MIT",
  bin: {
    fleetdeck: "bin/fleetdeck.mjs"
  },
  files: [
    "bin/",
    "compatibility.json",
    "src/daemon/fleetd.bundle.mjs",
    "src/daemon/board-dist/",
    "docs/CODER.md"
  ],
  author: "Luis Morales <luismmorales@gmail.com>",
  repository: {
    type: "git",
    url: "git+https://github.com/lacion/fleet-deck.git"
  },
  bugs: {
    url: "https://github.com/lacion/fleet-deck/issues"
  },
  homepage: "https://github.com/lacion/fleet-deck#readme",
  keywords: [
    "claude-code",
    "claude",
    "plugin",
    "tmux",
    "agents",
    "orchestration",
    "dashboard",
    "fleet"
  ],
  scripts: {
    start: "bun src/daemon/fleetd.ts",
    test: "bun test --timeout 300000",
    "test:bundle": "FLEETDECK_TEST_DAEMON_SCRIPT=$PWD/src/daemon/fleetd.bundle.mjs bun test --timeout 300000",
    bundle: `esbuild src/daemon/fleetd.ts --bundle --platform=node --format=esm --outfile=src/daemon/fleetd.bundle.mjs --external:bun:sqlite --banner:js="// GENERATED by 'bun run bundle' \u2014 do not edit. Source: src/daemon/*.ts
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);"`,
    "bundle:bin": `esbuild bin/fleetdeck.ts --bundle --platform=node --format=esm --outfile=bin/fleetdeck.mjs --banner:js="// GENERATED by 'bun run bundle:bin' \u2014 do not edit. Source: bin/*.ts"`,
    "bundle:hooks": `esbuild scripts/fleet-hook.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-hook.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts" && esbuild scripts/fleet-sessionstart.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-sessionstart.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts" && esbuild scripts/fleet-watch.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-watch.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts"`,
    "build:board": "cd board && bun install && bun run build",
    smoke: "bash demo/run-smoke.sh",
    typecheck: "tsc --noEmit -p tsconfig.json && tsc --noEmit -p board/tsconfig.json",
    "typecheck:board-tests": "tsc --noEmit -p tsconfig.board-tests.json",
    lint: "biome lint",
    "lint:fix": "biome lint --write",
    format: "biome format --write",
    "format:check": "biome format",
    ci: "biome ci"
  },
  engines: {
    bun: ">=1.3.14"
  },
  dependencies: {},
  devDependencies: {
    "@biomejs/biome": "2.5.8",
    "@types/bun": "^1.3.14",
    "@types/node": "22",
    "@types/ws": "^8.18.1",
    esbuild: "^0.28.1",
    typescript: "5.9.3",
    ws: "^8.18.0"
  }
};

// src/daemon/run-nonce.ts
import fs2 from "node:fs";
var isPid = (v) => typeof v === "number" && Number.isInteger(v) && v > 0;
function claudeAncestor(startPid) {
  let pid = startPid;
  for (let hops = 0; hops < 12 && isPid(pid) && pid > 1; hops += 1) {
    let comm;
    try {
      comm = fs2.readFileSync(`/proc/${pid}/comm`, "utf8").trim();
    } catch {
      return null;
    }
    if (comm === "claude") return pid;
    let stat;
    try {
      stat = fs2.readFileSync(`/proc/${pid}/stat`, "utf8");
    } catch {
      return null;
    }
    const tail = stat.slice(stat.lastIndexOf(")") + 1).trim().split(/\s+/);
    const parent = Number(tail[1]);
    if (!isPid(parent)) return null;
    pid = parent;
  }
  return null;
}
function runKey(env = process.env, ppid = process.ppid) {
  const declared = Number(env["CLAUDE_PID"]);
  if (isPid(declared)) return { key: declared, source: "CLAUDE_PID" };
  const walked = process.platform === "linux" ? claudeAncestor(ppid) : null;
  if (isPid(walked)) return { key: walked, source: "proc-ancestor" };
  return { key: ppid, source: "ppid" };
}

// scripts/claude-compat.ts
var DARWIN_GENERATION_PROBE_TIMEOUT_MS = 150;
var MAX_VERDICT_BYTES = 4096;
var VERDICT_LIFETIME_MS = 30 * 24 * 36e5;
var STALE_RETENTION_MS = VERDICT_LIFETIME_MS + 24 * 36e5;
var POLICY = compatibility_default;
var FLEETDECK_VERSION = package_default.version;
function parseStableClaudeVersion(output) {
  if (typeof output !== "string") return null;
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?: \(Claude Code\))?$/.exec(
    output.trim()
  );
  if (!match) return null;
  const parts = [Number(match[1]), Number(match[2]), Number(match[3])];
  if (parts.some((part) => !Number.isSafeInteger(part))) return null;
  return { raw: `${parts[0]}.${parts[1]}.${parts[2]}`, parts };
}
function compareVersion(a, b) {
  for (let i = 0; i < 3; i += 1) {
    const delta = (a.parts[i] ?? 0) - (b.parts[i] ?? 0);
    if (delta !== 0) return delta;
  }
  return 0;
}
function normalizedPolicy(policy) {
  if (policy.schema !== 1) return null;
  const min = parseStableClaudeVersion(policy.claudeCode?.min);
  const max = parseStableClaudeVersion(policy.claudeCode?.max);
  if (!min || !max || compareVersion(min, max) > 0) return null;
  return { min, max, signature: `1:${min.raw}:${max.raw}` };
}
function supportsClaudeVersion(version, policy = POLICY) {
  const parsed = parseStableClaudeVersion(version);
  const normalized = normalizedPolicy(policy);
  return Boolean(
    parsed && normalized && compareVersion(parsed, normalized.min) >= 0 && compareVersion(parsed, normalized.max) <= 0
  );
}
function identity(env, ppid) {
  return runKey(env, ppid);
}
function compatibilityVerdictFile(home, env = process.env, ppid = process.ppid) {
  return path2.join(home, `claude-compat-${identity(env, ppid).key}.json`);
}
function policySignature(policy) {
  return normalizedPolicy(policy)?.signature ?? null;
}
function linuxExecutable(pid) {
  try {
    const executable = fs3.readlinkSync(`/proc/${pid}/exe`);
    return path2.isAbsolute(executable) ? executable : null;
  } catch {
    return null;
  }
}
function lsofExecutable(output) {
  return output.split(/\r?\n/).find((line) => line.startsWith("n") && path2.isAbsolute(line.slice(1)))?.slice(1) ?? null;
}
function macExecutableSync(pid) {
  try {
    if (!fs3.existsSync("/usr/sbin/lsof")) return null;
    const output = execFileSync("/usr/sbin/lsof", ["-a", "-p", String(pid), "-d", "txt", "-Fn"], {
      encoding: "utf8",
      maxBuffer: 16 * 1024,
      timeout: DARWIN_GENERATION_PROBE_TIMEOUT_MS,
      killSignal: "SIGKILL",
      stdio: ["ignore", "pipe", "pipe"]
    });
    return lsofExecutable(output);
  } catch {
    return null;
  }
}
function executableFingerprint(executable) {
  try {
    const stat = fs3.statSync(executable);
    if (!stat.isFile()) return null;
    return {
      path: executable,
      dev: String(stat.dev),
      ino: String(stat.ino),
      size: stat.size,
      mtimeMs: stat.mtimeMs
    };
  } catch {
    return null;
  }
}
function linuxStartTicks(pid) {
  try {
    const stat = fs3.readFileSync(`/proc/${pid}/stat`, "utf8");
    const tail = stat.slice(stat.lastIndexOf(")") + 1).trim().split(/\s+/);
    const startTicks = tail[19];
    return typeof startTicks === "string" && /^\d+$/.test(startTicks) ? startTicks : null;
  } catch {
    return null;
  }
}
function darwinStartToken(pid) {
  try {
    const output = execFileSync("/bin/ps", ["-o", "lstart=", "-p", String(pid)], {
      encoding: "utf8",
      maxBuffer: 4096,
      timeout: DARWIN_GENERATION_PROBE_TIMEOUT_MS,
      killSignal: "SIGKILL",
      stdio: ["ignore", "pipe", "pipe"]
    });
    const token = output.trim().replace(/\s+/g, " ");
    return token && !token.includes("\n") ? token : null;
  } catch {
    return null;
  }
}
function testGeneration(env, processIdentity) {
  return {
    kind: "test",
    value: `${processIdentity.key}:${env["FLEETDECK_TEST_CLAUDE_VERSION"] ?? ""}`
  };
}
function sameExecutable(a, b) {
  return a.path === b.path && a.dev === b.dev && a.ino === b.ino && a.size === b.size && a.mtimeMs === b.mtimeMs;
}
function sameDarwinProcessGeneration(expectedStart, expectedExecutable, currentStart, currentExecutable) {
  return Boolean(
    currentStart && currentExecutable && currentStart === expectedStart && sameExecutable(currentExecutable, expectedExecutable)
  );
}
function generationIsCurrent(expected, processIdentity, env) {
  if (expected.kind === "test") {
    return env["FLEETDECK_TEST_CLAUDE_VERSION"] !== void 0 && expected.value === testGeneration(env, processIdentity).value;
  }
  try {
    process.kill(processIdentity.key, 0);
  } catch {
    return false;
  }
  if (expected.kind === "linux") {
    const executable = linuxExecutable(processIdentity.key);
    const fingerprint2 = executable ? executableFingerprint(executable) : null;
    return Boolean(
      fingerprint2 && linuxStartTicks(processIdentity.key) === expected.startTicks && sameExecutable(fingerprint2, expected.executable)
    );
  }
  const currentExecutable = macExecutableSync(processIdentity.key);
  const fingerprint = currentExecutable ? executableFingerprint(currentExecutable) : null;
  return sameDarwinProcessGeneration(
    expected.startToken,
    expected.executable,
    darwinStartToken(processIdentity.key),
    fingerprint
  );
}
function verdictIsOwnerOnly(file) {
  try {
    const stat = fs3.statSync(file);
    if (!stat.isFile() || (stat.mode & 63) !== 0) return false;
    return typeof process.getuid !== "function" || stat.uid === process.getuid();
  } catch {
    return false;
  }
}
function hasActiveClaudeCompatibility(home, options = {}) {
  const env = options.env ?? process.env;
  const ppid = options.ppid ?? process.ppid;
  const expectedIdentity = identity(env, ppid);
  const policy = options.policy ?? POLICY;
  const signature = policySignature(policy);
  if (!signature) return false;
  const fleetdeckVersion = options.fleetdeckVersion ?? FLEETDECK_VERSION;
  const now = options.now ?? Date.now();
  const file = compatibilityVerdictFile(home, env, ppid);
  if (!verdictIsOwnerOnly(file)) return false;
  try {
    const stat = fs3.statSync(file);
    if (stat.size <= 0 || stat.size > MAX_VERDICT_BYTES) return false;
    const parsed = JSON.parse(fs3.readFileSync(file, "utf8"));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return false;
    const verdict = parsed;
    return verdict.schema === 1 && verdict.identity?.key === expectedIdentity.key && verdict.identity.source === expectedIdentity.source && verdict.fleetdeckVersion === fleetdeckVersion && verdict.policy === signature && verdict.active === true && typeof verdict.createdAt === "number" && typeof verdict.expiresAt === "number" && verdict.createdAt <= now + 6e4 && verdict.expiresAt >= now && verdict.expiresAt - verdict.createdAt === VERDICT_LIFETIME_MS && verdict.generation !== void 0 && generationIsCurrent(verdict.generation, expectedIdentity, env) && supportsClaudeVersion(verdict.claudeVersion, policy);
  } catch {
    return false;
  }
}

// scripts/fleet-watch.ts
var runtime = null;
try {
  const home = resolveHome();
  if (!hasActiveClaudeCompatibility(home)) process.exit(0);
  const port = resolvePort();
  runtime = { base: resolveBase(port), home };
} catch {
  process.exit(0);
}
if (!runtime) process.exit(0);
var BASE = runtime.base;
var HOME = runtime.home;
var TOKEN = readToken(HOME);
var authHeaders = {};
if (TOKEN) authHeaders.authorization = `Bearer ${TOKEN}`;
function envMs(name, dflt, min, max) {
  const raw2 = Number(process.env[name]);
  if (!Number.isFinite(raw2) || raw2 <= 0) return dflt;
  return Math.max(min, Math.min(raw2, max));
}
var POLL_MS = envMs("FLEETDECK_WATCH_POLL_MS", 25e3, 50, 25e3);
var MAX_MS = envMs("FLEETDECK_WATCH_MAX_MS", 72e5, 500, 24 * 36e5);
var MAX_FAILURES = 3;
var MAX_STDIN_BYTES = 64e3;
var WAKE_FLUSH_MS = 1e3;
var startedAt = Date.now();
var sleep = (ms) => new Promise((r) => {
  setTimeout(r, ms);
});
var jitter = (base) => base + Math.floor(Math.random() * 250);
async function writeWake(text) {
  await new Promise((resolve) => {
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve();
    };
    const timer = setTimeout(finish, WAKE_FLUSH_MS);
    try {
      process.stderr.write(text, finish);
    } catch {
      finish();
    }
  });
}
function readStdin(timeoutMs = 5e3) {
  return new Promise((resolve) => {
    const chunks = [];
    let bytes = 0;
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      process.stdin.removeListener("data", onData);
      process.stdin.removeListener("end", finish);
      process.stdin.removeListener("error", finish);
      process.stdin.pause();
      resolve(Buffer.concat(chunks, bytes).toString("utf8"));
    };
    const onData = (chunk) => {
      const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
      const room = MAX_STDIN_BYTES - bytes;
      if (room > 0) {
        const kept = buf.length <= room ? buf : buf.subarray(0, room);
        chunks.push(kept);
        bytes += kept.length;
      }
      if (bytes >= MAX_STDIN_BYTES) finish();
    };
    const timer = setTimeout(finish, timeoutMs);
    process.stdin.on("data", onData);
    process.stdin.on("end", finish);
    process.stdin.on("error", finish);
  });
}
var pidFile = null;
function readPidFile() {
  if (!pidFile) return null;
  try {
    return fs4.readFileSync(pidFile, "utf8").trim();
  } catch {
    return null;
  }
}
function ownsPidFile() {
  return readPidFile() === String(process.pid);
}
function cleanupPidFile() {
  try {
    if (pidFile && ownsPidFile()) fs4.unlinkSync(pidFile);
  } catch {
  }
}
process.on("exit", cleanupPidFile);
var raw = await readStdin();
var payload = {};
try {
  payload = JSON.parse(raw || "{}");
} catch {
  process.exit(0);
}
var sid = payload.session_id;
if (!sid || typeof sid !== "string") process.exit(0);
try {
  fs4.mkdirSync(HOME, { recursive: true });
  pidFile = path3.join(HOME, `watch-${sid.replace(/[^A-Za-z0-9_.-]/g, "_")}.pid`);
  fs4.writeFileSync(pidFile, String(process.pid));
} catch {
  process.exit(0);
}
await sleep(150);
if (!ownsPidFile()) {
  pidFile = null;
  process.exit(0);
}
var GEN = randomUUID();
var failures = 0;
var deadline = startedAt + MAX_MS;
while (Date.now() < deadline) {
  if (!ownsPidFile()) {
    pidFile = null;
    process.exit(0);
  }
  const holdMs = Math.max(0, Math.min(POLL_MS, deadline - Date.now()));
  let out;
  try {
    const res = await fetch(
      `${BASE}/api/watch?session=${encodeURIComponent(sid)}&hold_ms=${holdMs}&wg=${encodeURIComponent(GEN)}`,
      {
        headers: authHeaders,
        signal: AbortSignal.timeout(holdMs + 5e3)
      }
    );
    if (!res.ok) throw new Error(`watch ${res.status}`);
    out = await res.json();
  } catch {
    failures += 1;
    if (failures >= MAX_FAILURES) process.exit(0);
    await sleep(jitter(Math.min(POLL_MS, 1e3)));
    continue;
  }
  failures = 0;
  if (!ownsPidFile()) {
    pidFile = null;
    process.exit(0);
  }
  if (out && (out.status === "mail" || out.status === "answer") && typeof out.text === "string") {
    const mailText = out.text;
    cleanupPidFile();
    if (out.status === "mail" && Number.isSafeInteger(out.mail_id)) {
      try {
        await fetch(`${BASE}/mail/ack`, {
          method: "POST",
          headers: {
            "content-type": "application/json",
            ...authHeaders
          },
          body: JSON.stringify({ mail_id: out.mail_id }),
          signal: AbortSignal.timeout(2e3)
        });
      } catch {
      }
    }
    await writeWake(mailText);
    process.exit(2);
  }
  if (out?.session_alive === false) process.exit(0);
  await sleep(out?.pending ? jitter(100) : jitter(Math.min(POLL_MS, 800)));
}
process.exit(0);
