#!/usr/bin/env bun
// GENERATED by 'bun run bundle:hooks' — do not edit. Source: scripts/fleet-*.ts

// scripts/fleet-watch.ts
import fs from "node:fs";
import path2 from "node:path";
import { randomUUID } from "node:crypto";

// src/daemon/config.ts
import os from "node:os";
import path from "node:path";
function resolveHome() {
  const fallbackBase = os.homedir() || "/tmp";
  const configured = process.env["FLEETDECK_HOME"]?.trim();
  if (!configured) return path.join(fallbackBase, ".fleetdeck");
  if (!path.isAbsolute(configured)) return path.resolve(fallbackBase, configured);
  return path.normalize(configured);
}
function resolvePort() {
  const raw2 = process.env["FLEETDECK_PORT"];
  if (raw2 === void 0 || raw2 === "") return 4711;
  const port = Number(raw2);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(
      `invalid FLEETDECK_PORT ${JSON.stringify(raw2)} \u2014 expected an integer port in 1..65535 (port 0 is not supported)`
    );
  }
  return port;
}
function resolveBase(port = resolvePort()) {
  return `http://127.0.0.1:${port}`;
}

// scripts/fleet-watch.ts
var PORT = resolvePort();
var BASE = resolveBase(PORT);
var HOME = resolveHome();
var TOKEN = null;
try {
  TOKEN = fs.readFileSync(path2.join(HOME, "token"), "utf8").trim() || null;
} catch {
}
var authHeaders = {};
if (TOKEN) authHeaders.authorization = `Bearer ${TOKEN}`;
function envMs(name, dflt, min, max) {
  const raw2 = Number(process.env[name]);
  if (!Number.isFinite(raw2) || raw2 <= 0) return dflt;
  return Math.max(min, Math.min(raw2, max));
}
var POLL_MS = envMs("FLEETDECK_WATCH_POLL_MS", 25e3, 50, 25e3);
var MAX_MS = envMs("FLEETDECK_WATCH_MAX_MS", 72e5, 500, 24 * 36e5);
var MAX_FAILURES = 3;
var MAX_STDIN_BYTES = 64e3;
var startedAt = Date.now();
var sleep = (ms) => new Promise((r) => {
  setTimeout(r, ms);
});
var jitter = (base) => base + Math.floor(Math.random() * 250);
function readStdin(timeoutMs = 5e3) {
  return new Promise((resolve) => {
    const chunks = [];
    let bytes = 0;
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      process.stdin.removeListener("data", onData);
      process.stdin.removeListener("end", finish);
      process.stdin.removeListener("error", finish);
      process.stdin.pause();
      resolve(Buffer.concat(chunks, bytes).toString("utf8"));
    };
    const onData = (chunk) => {
      const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
      const room = MAX_STDIN_BYTES - bytes;
      if (room > 0) {
        const kept = buf.length <= room ? buf : buf.subarray(0, room);
        chunks.push(kept);
        bytes += kept.length;
      }
      if (bytes >= MAX_STDIN_BYTES) finish();
    };
    const timer = setTimeout(finish, timeoutMs);
    process.stdin.on("data", onData);
    process.stdin.on("end", finish);
    process.stdin.on("error", finish);
  });
}
var pidFile = null;
function readPidFile() {
  if (!pidFile) return null;
  try {
    return fs.readFileSync(pidFile, "utf8").trim();
  } catch {
    return null;
  }
}
function ownsPidFile() {
  return readPidFile() === String(process.pid);
}
function cleanupPidFile() {
  try {
    if (pidFile && ownsPidFile()) fs.unlinkSync(pidFile);
  } catch {
  }
}
process.on("exit", cleanupPidFile);
var raw = await readStdin();
var payload = {};
try {
  payload = JSON.parse(raw || "{}");
} catch {
  process.exit(0);
}
var sid = payload.session_id;
if (!sid || typeof sid !== "string") process.exit(0);
try {
  fs.mkdirSync(HOME, { recursive: true });
  pidFile = path2.join(HOME, `watch-${sid.replace(/[^A-Za-z0-9_.-]/g, "_")}.pid`);
  fs.writeFileSync(pidFile, String(process.pid));
} catch {
  process.exit(0);
}
await sleep(150);
if (!ownsPidFile()) {
  pidFile = null;
  process.exit(0);
}
var GEN = randomUUID();
var failures = 0;
var deadline = startedAt + MAX_MS;
while (Date.now() < deadline) {
  if (!ownsPidFile()) {
    pidFile = null;
    process.exit(0);
  }
  const holdMs = Math.max(0, Math.min(POLL_MS, deadline - Date.now()));
  let out;
  try {
    const res = await fetch(
      `${BASE}/api/watch?session=${encodeURIComponent(sid)}&hold_ms=${holdMs}&wg=${encodeURIComponent(GEN)}`,
      {
        headers: authHeaders,
        signal: AbortSignal.timeout(holdMs + 5e3)
      }
    );
    if (!res.ok) throw new Error(`watch ${res.status}`);
    out = await res.json();
  } catch {
    failures += 1;
    if (failures >= MAX_FAILURES) process.exit(0);
    await sleep(jitter(Math.min(POLL_MS, 1e3)));
    continue;
  }
  failures = 0;
  if (!ownsPidFile()) {
    pidFile = null;
    process.exit(0);
  }
  if (out && (out.status === "mail" || out.status === "answer") && typeof out.text === "string") {
    cleanupPidFile();
    if (out.status === "mail" && Number.isSafeInteger(out.mail_id)) {
      try {
        await fetch(`${BASE}/mail/ack`, {
          method: "POST",
          headers: {
            "content-type": "application/json",
            ...authHeaders
          },
          body: JSON.stringify({ mail_id: out.mail_id }),
          signal: AbortSignal.timeout(2e3)
        });
      } catch {
      }
    }
    process.stderr.write(out.text);
    process.exit(2);
  }
  if (out?.session_alive === false) process.exit(0);
  await sleep(out?.pending ? jitter(100) : jitter(Math.min(POLL_MS, 800)));
}
process.exit(0);
