#!/usr/bin/env bun
// GENERATED by 'bun run bundle:hooks' — do not edit. Source: scripts/fleet-*.ts

// src/daemon/config.ts
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
function resolveHome() {
  const fallbackBase = os.homedir() || "/tmp";
  const configured = process.env["FLEETDECK_HOME"]?.trim();
  if (!configured) return path.join(fallbackBase, ".fleetdeck");
  if (!path.isAbsolute(configured)) return path.resolve(fallbackBase, configured);
  return path.normalize(configured);
}
function resolvePort() {
  const raw = process.env["FLEETDECK_PORT"];
  if (raw === void 0 || raw === "") return 4711;
  const port = Number(raw);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(
      `invalid FLEETDECK_PORT ${JSON.stringify(raw)} \u2014 expected an integer port in 1..65535 (port 0 is not supported)`
    );
  }
  return port;
}
function resolveBase(port = resolvePort()) {
  return `http://127.0.0.1:${port}`;
}
function readToken(home) {
  try {
    return fs.readFileSync(path.join(home, "token"), "utf8").trim() || null;
  } catch {
    return null;
  }
}

// src/daemon/run-nonce.ts
import fs2 from "node:fs";
import path2 from "node:path";
import { randomUUID } from "node:crypto";
var isPid = (v) => typeof v === "number" && Number.isInteger(v) && v > 0;
function claudeAncestor(startPid) {
  let pid = startPid;
  for (let hops = 0; hops < 12 && isPid(pid) && pid > 1; hops += 1) {
    let comm;
    try {
      comm = fs2.readFileSync(`/proc/${pid}/comm`, "utf8").trim();
    } catch {
      return null;
    }
    if (comm === "claude") return pid;
    let stat;
    try {
      stat = fs2.readFileSync(`/proc/${pid}/stat`, "utf8");
    } catch {
      return null;
    }
    const tail = stat.slice(stat.lastIndexOf(")") + 1).trim().split(/\s+/);
    const parent = Number(tail[1]);
    if (!isPid(parent)) return null;
    pid = parent;
  }
  return null;
}
function runKey(env = process.env, ppid = process.ppid) {
  const declared = Number(env["CLAUDE_PID"]);
  if (isPid(declared)) return { key: declared, source: "CLAUDE_PID" };
  const walked = process.platform === "linux" ? claudeAncestor(ppid) : null;
  if (isPid(walked)) return { key: walked, source: "proc-ancestor" };
  return { key: ppid, source: "ppid" };
}
var runFileFor = (home, key) => path2.join(home, `run-${key}`);
function runNonce(home, env = process.env, ppid = process.ppid) {
  if (!home) return null;
  try {
    const file = runFileFor(home, runKey(env, ppid).key);
    try {
      const existing = fs2.readFileSync(file, "utf8").trim();
      if (existing) return existing;
    } catch {
    }
    const minted = randomUUID();
    fs2.writeFileSync(file, minted, { mode: 384 });
    return minted;
  } catch {
    return null;
  }
}

// scripts/claude-compat.ts
import { execFile, execFileSync } from "node:child_process";
import fs3 from "node:fs";
import path3 from "node:path";

// compatibility.json
var compatibility_default = {
  schema: 2,
  claudeCode: {
    min: "2.1.206"
  }
};

// package.json
var package_default = {
  name: "fleetdeck",
  version: "0.23.5",
  description: "Fleet Deck \u2014 localhost daemon + board for Claude Code, guarded by a release-bound compatibility policy.",
  type: "module",
  license: "MIT",
  bin: {
    fleetdeck: "bin/fleetdeck.mjs"
  },
  files: [
    "bin/",
    "compatibility.json",
    "src/daemon/fleetd.bundle.mjs",
    "src/daemon/board-dist/",
    "docs/CODER.md"
  ],
  author: "Luis Morales <luismmorales@gmail.com>",
  repository: {
    type: "git",
    url: "git+https://github.com/lacion/fleet-deck.git"
  },
  bugs: {
    url: "https://github.com/lacion/fleet-deck/issues"
  },
  homepage: "https://github.com/lacion/fleet-deck#readme",
  keywords: [
    "claude-code",
    "claude",
    "plugin",
    "tmux",
    "agents",
    "orchestration",
    "dashboard",
    "fleet"
  ],
  scripts: {
    start: "bun src/daemon/fleetd.ts",
    test: "bun test --timeout 300000",
    "test:bundle": "FLEETDECK_TEST_DAEMON_SCRIPT=$PWD/src/daemon/fleetd.bundle.mjs bun test --timeout 300000",
    bundle: `esbuild src/daemon/fleetd.ts --bundle --platform=node --format=esm --outfile=src/daemon/fleetd.bundle.mjs --external:bun:sqlite --banner:js="// GENERATED by 'bun run bundle' \u2014 do not edit. Source: src/daemon/*.ts
import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);"`,
    "bundle:bin": `esbuild bin/fleetdeck.ts --bundle --platform=node --format=esm --outfile=bin/fleetdeck.mjs --banner:js="// GENERATED by 'bun run bundle:bin' \u2014 do not edit. Source: bin/*.ts"`,
    "bundle:hooks": `esbuild scripts/fleet-hook.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-hook.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts" && esbuild scripts/fleet-sessionstart.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-sessionstart.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts" && esbuild scripts/fleet-watch.ts --bundle --platform=node --format=esm --outfile=scripts/fleet-watch.mjs --banner:js="// GENERATED by 'bun run bundle:hooks' \u2014 do not edit. Source: scripts/fleet-*.ts"`,
    "build:board": "cd board && bun install && bun run build",
    smoke: "bash demo/run-smoke.sh",
    typecheck: "tsc --noEmit -p tsconfig.json && tsc --noEmit -p board/tsconfig.json",
    "typecheck:board-tests": "tsc --noEmit -p tsconfig.board-tests.json",
    lint: "biome lint",
    "lint:fix": "biome lint --write",
    format: "biome format --write",
    "format:check": "biome format",
    ci: "biome ci"
  },
  engines: {
    bun: ">=1.3.14"
  },
  dependencies: {},
  devDependencies: {
    "@biomejs/biome": "2.5.8",
    "@types/bun": "^1.3.14",
    "@types/node": "22",
    "@types/ws": "^8.18.1",
    esbuild: "^0.28.1",
    typescript: "5.9.3",
    ws: "^8.18.0"
  }
};

// scripts/claude-compat.ts
var DARWIN_GENERATION_PROBE_TIMEOUT_MS = 150;
var MAX_VERDICT_BYTES = 4096;
var VERDICT_LIFETIME_MS = 30 * 24 * 36e5;
var STALE_RETENTION_MS = VERDICT_LIFETIME_MS + 24 * 36e5;
var POLICY = compatibility_default;
var FLEETDECK_VERSION = package_default.version;
function parseStableClaudeVersion(output2) {
  if (typeof output2 !== "string") return null;
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?: \(Claude Code\))?$/.exec(
    output2.trim()
  );
  if (!match) return null;
  const parts = [Number(match[1]), Number(match[2]), Number(match[3])];
  if (parts.some((part) => !Number.isSafeInteger(part))) return null;
  return { raw: `${parts[0]}.${parts[1]}.${parts[2]}`, parts };
}
function compareVersion(a, b) {
  for (let i = 0; i < 3; i += 1) {
    const delta = (a.parts[i] ?? 0) - (b.parts[i] ?? 0);
    if (delta !== 0) return delta;
  }
  return 0;
}
function normalizedPolicy(policy) {
  if (policy.schema !== 2) return null;
  const min = parseStableClaudeVersion(policy.claudeCode?.min);
  if (!min) return null;
  return { min, signature: `2:${min.raw}` };
}
function supportsClaudeVersion(version, policy = POLICY) {
  const parsed = parseStableClaudeVersion(version);
  const normalized = normalizedPolicy(policy);
  return Boolean(parsed && normalized && compareVersion(parsed, normalized.min) >= 0);
}
function identity(env, ppid) {
  return runKey(env, ppid);
}
function compatibilityVerdictFile(home, env = process.env, ppid = process.ppid) {
  return path3.join(home, `claude-compat-${identity(env, ppid).key}.json`);
}
function policySignature(policy) {
  return normalizedPolicy(policy)?.signature ?? null;
}
function linuxExecutable(pid) {
  try {
    const executable = fs3.readlinkSync(`/proc/${pid}/exe`);
    return path3.isAbsolute(executable) ? executable : null;
  } catch {
    return null;
  }
}
function lsofExecutable(output2) {
  return output2.split(/\r?\n/).find((line) => line.startsWith("n") && path3.isAbsolute(line.slice(1)))?.slice(1) ?? null;
}
function macExecutableSync(pid) {
  try {
    if (!fs3.existsSync("/usr/sbin/lsof")) return null;
    const output2 = execFileSync("/usr/sbin/lsof", ["-a", "-p", String(pid), "-d", "txt", "-Fn"], {
      encoding: "utf8",
      maxBuffer: 16 * 1024,
      timeout: DARWIN_GENERATION_PROBE_TIMEOUT_MS,
      killSignal: "SIGKILL",
      stdio: ["ignore", "pipe", "pipe"]
    });
    return lsofExecutable(output2);
  } catch {
    return null;
  }
}
function executableFingerprint(executable) {
  try {
    const stat = fs3.statSync(executable);
    if (!stat.isFile()) return null;
    return {
      path: executable,
      dev: String(stat.dev),
      ino: String(stat.ino),
      size: stat.size,
      mtimeMs: stat.mtimeMs
    };
  } catch {
    return null;
  }
}
function linuxStartTicks(pid) {
  try {
    const stat = fs3.readFileSync(`/proc/${pid}/stat`, "utf8");
    const tail = stat.slice(stat.lastIndexOf(")") + 1).trim().split(/\s+/);
    const startTicks = tail[19];
    return typeof startTicks === "string" && /^\d+$/.test(startTicks) ? startTicks : null;
  } catch {
    return null;
  }
}
function darwinStartToken(pid) {
  try {
    const output2 = execFileSync("/bin/ps", ["-o", "lstart=", "-p", String(pid)], {
      encoding: "utf8",
      maxBuffer: 4096,
      timeout: DARWIN_GENERATION_PROBE_TIMEOUT_MS,
      killSignal: "SIGKILL",
      stdio: ["ignore", "pipe", "pipe"]
    });
    const token = output2.trim().replace(/\s+/g, " ");
    return token && !token.includes("\n") ? token : null;
  } catch {
    return null;
  }
}
function testGeneration(env, processIdentity) {
  return {
    kind: "test",
    value: `${processIdentity.key}:${env["FLEETDECK_TEST_CLAUDE_VERSION"] ?? ""}`
  };
}
function sameExecutable(a, b) {
  return a.path === b.path && a.dev === b.dev && a.ino === b.ino && a.size === b.size && a.mtimeMs === b.mtimeMs;
}
function sameDarwinProcessGeneration(expectedStart, expectedExecutable, currentStart, currentExecutable) {
  return Boolean(
    currentStart && currentExecutable && currentStart === expectedStart && sameExecutable(currentExecutable, expectedExecutable)
  );
}
function generationIsCurrent(expected, processIdentity, env) {
  if (expected.kind === "test") {
    return env["FLEETDECK_TEST_CLAUDE_VERSION"] !== void 0 && expected.value === testGeneration(env, processIdentity).value;
  }
  try {
    process.kill(processIdentity.key, 0);
  } catch {
    return false;
  }
  if (expected.kind === "linux") {
    const executable = linuxExecutable(processIdentity.key);
    const fingerprint2 = executable ? executableFingerprint(executable) : null;
    return Boolean(
      fingerprint2 && linuxStartTicks(processIdentity.key) === expected.startTicks && sameExecutable(fingerprint2, expected.executable)
    );
  }
  const currentExecutable = macExecutableSync(processIdentity.key);
  const fingerprint = currentExecutable ? executableFingerprint(currentExecutable) : null;
  return sameDarwinProcessGeneration(
    expected.startToken,
    expected.executable,
    darwinStartToken(processIdentity.key),
    fingerprint
  );
}
function verdictIsOwnerOnly(file) {
  try {
    const stat = fs3.statSync(file);
    if (!stat.isFile() || (stat.mode & 63) !== 0) return false;
    return typeof process.getuid !== "function" || stat.uid === process.getuid();
  } catch {
    return false;
  }
}
function hasActiveClaudeCompatibility(home, options = {}) {
  const env = options.env ?? process.env;
  const ppid = options.ppid ?? process.ppid;
  const expectedIdentity = identity(env, ppid);
  const policy = options.policy ?? POLICY;
  const signature = policySignature(policy);
  if (!signature) return false;
  const fleetdeckVersion = options.fleetdeckVersion ?? FLEETDECK_VERSION;
  const now = options.now ?? Date.now();
  const file = compatibilityVerdictFile(home, env, ppid);
  if (!verdictIsOwnerOnly(file)) return false;
  try {
    const stat = fs3.statSync(file);
    if (stat.size <= 0 || stat.size > MAX_VERDICT_BYTES) return false;
    const parsed = JSON.parse(fs3.readFileSync(file, "utf8"));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return false;
    const verdict = parsed;
    return verdict.schema === 1 && verdict.identity?.key === expectedIdentity.key && verdict.identity.source === expectedIdentity.source && verdict.fleetdeckVersion === fleetdeckVersion && verdict.policy === signature && verdict.active === true && typeof verdict.createdAt === "number" && typeof verdict.expiresAt === "number" && verdict.createdAt <= now + 6e4 && verdict.expiresAt >= now && verdict.expiresAt - verdict.createdAt === VERDICT_LIFETIME_MS && verdict.generation !== void 0 && generationIsCurrent(verdict.generation, expectedIdentity, env) && supportsClaudeVersion(verdict.claudeVersion, policy);
  } catch {
    return false;
  }
}

// scripts/hook-output.ts
var MAX_CONTEXT_CHARS = 1e4;
var MAX_STRUCTURED_JSON_BYTES = 256 * 1024;
var MAX_JSON_DEPTH = 12;
var MAX_JSON_NODES = 4096;
var FORBIDDEN_KEYS = /* @__PURE__ */ new Set(["__proto__", "constructor", "prototype"]);
function record(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value) ? value : null;
}
function exactKeys(value, required, optional = []) {
  const keys = Object.keys(value);
  const allowed = /* @__PURE__ */ new Set([...required, ...optional]);
  return required.every((key) => Object.hasOwn(value, key)) && keys.every((key) => allowed.has(key));
}
function safeJson(value) {
  let nodes = 0;
  const visit = (candidate, depth) => {
    nodes += 1;
    if (nodes > MAX_JSON_NODES || depth > MAX_JSON_DEPTH) return false;
    if (candidate === null || typeof candidate === "boolean" || typeof candidate === "string") {
      return true;
    }
    if (typeof candidate === "number") return Number.isFinite(candidate);
    if (Array.isArray(candidate)) return candidate.every((item) => visit(item, depth + 1));
    const obj = record(candidate);
    if (!obj) return false;
    return Object.entries(obj).every(
      ([key, nested]) => !FORBIDDEN_KEYS.has(key) && visit(nested, depth + 1)
    );
  };
  if (!visit(value, 0)) return false;
  try {
    return Buffer.byteLength(JSON.stringify(value)) <= MAX_STRUCTURED_JSON_BYTES;
  } catch {
    return false;
  }
}
function contextResponse(event, parsed) {
  if (!exactKeys(parsed, ["hookSpecificOutput"])) return null;
  const output2 = record(parsed["hookSpecificOutput"]);
  if (!output2 || !exactKeys(output2, ["hookEventName", "additionalContext"])) return null;
  if (output2["hookEventName"] !== event) return null;
  const context = output2["additionalContext"];
  if (typeof context !== "string" || !context || context.length > MAX_CONTEXT_CHARS) return null;
  return { hookSpecificOutput: { hookEventName: event, additionalContext: context } };
}
function stopResponse(parsed) {
  if (!exactKeys(parsed, ["decision", "reason"])) return null;
  const reason = parsed["reason"];
  if (parsed["decision"] !== "block" || typeof reason !== "string" || !reason) return null;
  if (reason.length > MAX_CONTEXT_CHARS) return null;
  return { decision: "block", reason };
}
function permissionResponse(parsed) {
  if (!exactKeys(parsed, ["hookSpecificOutput"])) return null;
  const output2 = record(parsed["hookSpecificOutput"]);
  if (!output2 || !exactKeys(output2, ["hookEventName", "decision"])) return null;
  if (output2["hookEventName"] !== "PermissionRequest") return null;
  const decision = record(output2["decision"]);
  if (!decision || !exactKeys(decision, ["behavior"])) return null;
  const behavior = decision["behavior"];
  if (behavior !== "allow" && behavior !== "deny") return null;
  return {
    hookSpecificOutput: { hookEventName: "PermissionRequest", decision: { behavior } }
  };
}
function askUserQuestionResponse(parsed, requestRaw) {
  if (!exactKeys(parsed, ["hookSpecificOutput"])) return null;
  const output2 = record(parsed["hookSpecificOutput"]);
  if (!output2 || !exactKeys(output2, ["hookEventName", "permissionDecision", "updatedInput"]) || output2["hookEventName"] !== "PreToolUse" || output2["permissionDecision"] !== "allow")
    return null;
  const updated = record(output2["updatedInput"]);
  if (!updated || !exactKeys(updated, ["questions", "answers"])) return null;
  const questions = updated["questions"];
  const answers = record(updated["answers"]);
  if (!Array.isArray(questions) || questions.length === 0 || !answers) return null;
  let expectedQuestions = null;
  try {
    expectedQuestions = record(record(JSON.parse(requestRaw))?.["tool_input"])?.["questions"];
  } catch {
    return null;
  }
  if (!Array.isArray(expectedQuestions) || JSON.stringify(questions) !== JSON.stringify(expectedQuestions))
    return null;
  const questionTexts = [];
  for (const candidate of questions) {
    const question = record(candidate)?.["question"];
    if (typeof question !== "string" || !question || questionTexts.includes(question)) return null;
    questionTexts.push(question);
  }
  const answerEntries = Object.entries(answers);
  if (answerEntries.length !== questionTexts.length || answerEntries.some(
    ([question, answer]) => !questionTexts.includes(question) || typeof answer !== "string" || !answer || answer.length > 2e3
  ) || !safeJson({ questions, answers }))
    return null;
  return {
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      updatedInput: { questions, answers }
    }
  };
}
function elicitationResponse(parsed) {
  if (!exactKeys(parsed, ["hookSpecificOutput"])) return null;
  const output2 = record(parsed["hookSpecificOutput"]);
  if (output2?.["hookEventName"] !== "Elicitation") return null;
  const action = output2["action"];
  if (action !== "accept" && action !== "decline" && action !== "cancel") return null;
  if (action === "accept") {
    if (!exactKeys(output2, ["hookEventName", "action", "content"])) return null;
    const content2 = record(output2["content"]);
    if (!content2 || !safeJson(content2)) return null;
    return { hookSpecificOutput: { hookEventName: "Elicitation", action, content: content2 } };
  }
  if (!exactKeys(output2, ["hookEventName", "action"], ["content"])) return null;
  const content = output2["content"];
  if (content !== void 0 && (record(content) === null || Object.keys(content).length > 0)) {
    return null;
  }
  return { hookSpecificOutput: { hookEventName: "Elicitation", action } };
}
function canonicalHookOutput(event, text, requestRaw = "{}") {
  if (!text || Buffer.byteLength(text) > 1024 * 1024) return "{}";
  let parsed;
  try {
    parsed = record(JSON.parse(text));
  } catch {
    return "{}";
  }
  if (!parsed) return "{}";
  if (Object.keys(parsed).length === 0) return "{}";
  let allowed = null;
  if (event === "UserPromptSubmit" || event === "PostToolUse" || event === "PostToolUseFailure") {
    allowed = contextResponse(event, parsed);
  } else if (event === "Stop") allowed = stopResponse(parsed);
  else if (event === "PermissionRequest") allowed = permissionResponse(parsed);
  else if (event === "AskUserQuestion") allowed = askUserQuestionResponse(parsed, requestRaw);
  else if (event === "Elicitation") allowed = elicitationResponse(parsed);
  return allowed ? JSON.stringify(allowed) : "{}";
}

// scripts/fleet-hook.ts
async function canonicalNoopAndExit() {
  const hardExit = setTimeout(() => process.exit(0), 100);
  try {
    await new Promise((resolve) => {
      process.stdout.write("{}", () => resolve());
    });
  } catch {
  } finally {
    clearTimeout(hardExit);
  }
  process.exit(0);
}
var EVENT = process.argv[2];
var runtime = null;
try {
  const home = resolveHome();
  if (!hasActiveClaudeCompatibility(home)) await canonicalNoopAndExit();
  const port = resolvePort();
  runtime = { home, base: resolveBase(port) };
} catch {
  await canonicalNoopAndExit();
}
if (!runtime) await canonicalNoopAndExit();
var readyRuntime = runtime;
var HOME = readyRuntime.home;
var BASE = readyRuntime.base;
var RUN = runNonce(HOME);
function withRun(raw) {
  if (!RUN) return raw;
  try {
    const parsed = raw ? JSON.parse(raw) : {};
    if (parsed && typeof parsed === "object") {
      const body = parsed;
      if (body.fleet_run == null) {
        body.fleet_run = RUN;
        return JSON.stringify(body);
      }
    }
  } catch {
  }
  return raw;
}
var HOLD_EVENTS = /* @__PURE__ */ new Set(["PermissionRequest", "Elicitation", "AskUserQuestion"]);
var BOARD_SESSION_MARKER = process.env["FLEETDECK_BOARD_SESSION"];
var HEALTH_PROBE_INTERVAL_MS = (() => {
  const n = Number(process.env["FLEETDECK_TEST_HOOK_HEALTH_INTERVAL_MS"]);
  return Number.isFinite(n) && n >= 25 ? Math.min(n, 4e3) : 4e3;
})();
var HEALTH_PROBE_TIMEOUT_MS = (() => {
  const n = Number(process.env["FLEETDECK_TEST_HOOK_HEALTH_TIMEOUT_MS"]);
  return Number.isFinite(n) && n >= 25 ? Math.min(n, 1500) : 1500;
})();
var HEALTH_PROBE_FAILURES = 3;
var watchdogMs = EVENT === "SessionEnd" ? 800 : 2500;
var outputStarted = false;
var failOpen = () => {
  if (outputStarted) return;
  outputStarted = true;
  const hardExit = setTimeout(() => process.exit(0), 100);
  try {
    process.stdout.write("{}", () => {
      clearTimeout(hardExit);
      process.exit(0);
    });
  } catch {
    clearTimeout(hardExit);
    process.exit(0);
  }
};
var watchdog = setTimeout(failOpen, watchdogMs);
function rearmWatchdog(ms) {
  clearTimeout(watchdog);
  watchdogMs = ms;
  watchdog = setTimeout(failOpen, watchdogMs);
}
function payloadSessionId(raw) {
  try {
    const parsed = JSON.parse(raw || "{}");
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return null;
    const sid = parsed.session_id;
    return typeof sid === "string" && sid ? sid : null;
  } catch {
    return null;
  }
}
function startDaemonLivenessLease(requestController, authorization) {
  let stopped = false;
  let failures = 0;
  let timer = null;
  let activeController = null;
  const probe = async () => {
    if (stopped) return;
    const ctl = new AbortController();
    activeController = ctl;
    const timeout = setTimeout(() => ctl.abort(), HEALTH_PROBE_TIMEOUT_MS);
    let healthy = false;
    try {
      const res = await fetch(`${BASE}/health`, {
        ...authorization ? { headers: { authorization } } : {},
        signal: ctl.signal
      });
      if (res.ok) {
        const body = await res.json();
        healthy = body !== null && typeof body === "object" && !Array.isArray(body) && body.ok === true;
      }
    } catch {
      healthy = false;
    } finally {
      clearTimeout(timeout);
      if (activeController === ctl) activeController = null;
    }
    if (stopped) return;
    failures = healthy ? 0 : failures + 1;
    if (failures >= HEALTH_PROBE_FAILURES) {
      requestController.abort();
      rearmWatchdog(500);
      return;
    }
    timer = setTimeout(() => {
      void probe();
    }, HEALTH_PROBE_INTERVAL_MS);
  };
  timer = setTimeout(() => {
    void probe();
  }, HEALTH_PROBE_INTERVAL_MS);
  return () => {
    stopped = true;
    if (timer) clearTimeout(timer);
    activeController?.abort();
    activeController = null;
  };
}
var TOKEN = readToken(HOME);
async function readStdinRaw() {
  const maxBytes = 1024 * 1024;
  let data = "";
  let bytes = 0;
  try {
    for await (const chunk of process.stdin) {
      if (bytes >= maxBytes) continue;
      const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk));
      const kept = buf.subarray(0, maxBytes - bytes);
      data += kept.toString("utf8");
      bytes += kept.length;
    }
  } catch {
  }
  return data;
}
var output = "{}";
try {
  const raw = await readStdinRaw();
  let longBoardHold = false;
  if (EVENT !== void 0 && HOLD_EVENTS.has(EVENT) && BOARD_SESSION_MARKER !== void 0 && BOARD_SESSION_MARKER !== "1" && payloadSessionId(raw) === BOARD_SESSION_MARKER) {
    longBoardHold = true;
    rearmWatchdog(66e4);
  }
  const headers = {
    "content-type": "application/json"
  };
  if (TOKEN) headers.authorization = `Bearer ${TOKEN}`;
  const ctl = new AbortController();
  const stopLivenessLease = longBoardHold ? startDaemonLivenessLease(ctl, TOKEN ? `Bearer ${TOKEN}` : null) : () => {
  };
  const t = setTimeout(() => {
    ctl.abort();
  }, watchdogMs - 400);
  try {
    const res = await fetch(`${BASE}/hook/${String(EVENT)}`, {
      method: "POST",
      headers,
      body: withRun(raw) || "{}",
      signal: ctl.signal
    });
    const text = await res.text();
    output = res.ok ? canonicalHookOutput(EVENT, text, raw) : "{}";
  } finally {
    stopLivenessLease();
    clearTimeout(t);
  }
} catch {
  output = "{}";
}
if (!outputStarted) {
  outputStarted = true;
  const hardExit = setTimeout(() => process.exit(0), 100);
  try {
    await new Promise((resolve) => {
      process.stdout.write(output, () => resolve());
    });
  } catch {
  } finally {
    clearTimeout(hardExit);
    clearTimeout(watchdog);
  }
}
process.exitCode = 0;
