#!/usr/bin/env bun
// GENERATED by 'bun run bundle:hooks' — do not edit. Source: scripts/fleet-*.ts

// src/daemon/config.ts
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
function resolveHome() {
  const fallbackBase = os.homedir() || "/tmp";
  const configured = process.env["FLEETDECK_HOME"]?.trim();
  if (!configured) return path.join(fallbackBase, ".fleetdeck");
  if (!path.isAbsolute(configured)) return path.resolve(fallbackBase, configured);
  return path.normalize(configured);
}
function resolvePort() {
  const raw = process.env["FLEETDECK_PORT"];
  if (raw === void 0 || raw === "") return 4711;
  const port = Number(raw);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(
      `invalid FLEETDECK_PORT ${JSON.stringify(raw)} \u2014 expected an integer port in 1..65535 (port 0 is not supported)`
    );
  }
  return port;
}
function resolveBase(port = resolvePort()) {
  return `http://127.0.0.1:${port}`;
}
function readToken(home) {
  try {
    return fs.readFileSync(path.join(home, "token"), "utf8").trim() || null;
  } catch {
    return null;
  }
}

// src/daemon/run-nonce.ts
import fs2 from "node:fs";
import path2 from "node:path";
import { randomUUID } from "node:crypto";
var isPid = (v) => typeof v === "number" && Number.isInteger(v) && v > 0;
function claudeAncestor(startPid) {
  let pid = startPid;
  for (let hops = 0; hops < 12 && isPid(pid) && pid > 1; hops += 1) {
    let comm;
    try {
      comm = fs2.readFileSync(`/proc/${pid}/comm`, "utf8").trim();
    } catch {
      return null;
    }
    if (comm === "claude") return pid;
    let stat;
    try {
      stat = fs2.readFileSync(`/proc/${pid}/stat`, "utf8");
    } catch {
      return null;
    }
    const tail = stat.slice(stat.lastIndexOf(")") + 1).trim().split(/\s+/);
    const parent = Number(tail[1]);
    if (!isPid(parent)) return null;
    pid = parent;
  }
  return null;
}
function runKey(env = process.env, ppid = process.ppid) {
  const declared = Number(env["CLAUDE_PID"]);
  if (isPid(declared)) return { key: declared, source: "CLAUDE_PID" };
  const walked = process.platform === "linux" ? claudeAncestor(ppid) : null;
  if (isPid(walked)) return { key: walked, source: "proc-ancestor" };
  return { key: ppid, source: "ppid" };
}
var runFileFor = (home, key) => path2.join(home, `run-${key}`);
function runNonce(home, env = process.env, ppid = process.ppid) {
  if (!home) return null;
  try {
    const file = runFileFor(home, runKey(env, ppid).key);
    try {
      const existing = fs2.readFileSync(file, "utf8").trim();
      if (existing) return existing;
    } catch {
    }
    const minted = randomUUID();
    fs2.writeFileSync(file, minted, { mode: 384 });
    return minted;
  } catch {
    return null;
  }
}

// scripts/fleet-hook.ts
var EVENT = process.argv[2];
var HOME = resolveHome();
var BASE = resolveBase(resolvePort());
var RUN = runNonce(HOME);
function withRun(raw) {
  if (!RUN) return raw;
  try {
    const parsed = raw ? JSON.parse(raw) : {};
    if (parsed && typeof parsed === "object") {
      const body = parsed;
      if (body.fleet_run == null) {
        body.fleet_run = RUN;
        return JSON.stringify(body);
      }
    }
  } catch {
  }
  return raw;
}
var HOLD_EVENTS = /* @__PURE__ */ new Set(["PermissionRequest", "Elicitation", "AskUserQuestion"]);
var WATCHDOG_MS = EVENT !== void 0 && HOLD_EVENTS.has(EVENT) ? 66e4 : 2500;
var watchdog = setTimeout(() => {
  try {
    process.stdout.write("{}");
  } catch {
  }
  process.exit(0);
}, WATCHDOG_MS);
var TOKEN = readToken(HOME);
async function readStdinRaw() {
  let data = "";
  try {
    for await (const chunk of process.stdin) {
      if (data.length < 1024 * 1024)
        data += typeof chunk === "string" ? chunk : chunk.toString("utf8");
    }
  } catch {
  }
  return data;
}
try {
  const raw = await readStdinRaw();
  const headers = {
    "content-type": "application/json"
  };
  if (TOKEN) headers.authorization = `Bearer ${TOKEN}`;
  const ctl = new AbortController();
  const t = setTimeout(() => {
    ctl.abort();
  }, WATCHDOG_MS - 400);
  try {
    const res = await fetch(`${BASE}/hook/${String(EVENT)}`, {
      method: "POST",
      headers,
      body: withRun(raw) || "{}",
      signal: ctl.signal
    });
    const text = await res.text();
    const body = res.ok && text ? text : "{}";
    process.stdout.write(body);
  } finally {
    clearTimeout(t);
  }
} catch {
  try {
    process.stdout.write("{}");
  } catch {
  }
}
clearTimeout(watchdog);
process.exit(0);
