// Post-bundle gzip-headroom lever for src/daemon/fleetd.bundle.mjs.
//
// Runs AFTER esbuild + the @__PURE__ strip stage in `bun run bundle`. It is a
// tokenizer-grade JS lexer that removes only three byte-classes from the
// generated ESM, never touching code, string literals, template literals, or
// regexes:
//
//   1. JSDoc block comments — a block comment whose third character is `*`
//      (`/**`). Replaced by an equal number of newlines so the artifact's total
//      LINE COUNT is preserved verbatim (the policy gate asserts > 10_000 lines).
//   2. esbuild file-path header line comments at column 0
//      (`// node_modules/effect/…/foo.js`). Blanked to an empty line. This costs
//      per-module file attribution in the bundle.
//   3. ALL other `//` line comments (the ~800 source comments esbuild carries
//      through because the recipe does not `--minify-whitespace`). A comment-only
//      line collapses to a genuinely empty line (its same-line leading indent is
//      trimmed too); a trailing comment on a code line is dropped WITHOUT joining
//      lines (the terminating newline is a separate token and is left intact).
//      This is the dominant lever (~26 KB gzip) and the reason the ceiling stops
//      being a recurring squeeze.
//
// Deliberately preserved: the shebang, the two-line GENERATED banner (matched by
// its `// GENERATED by 'bun run bundle'` text, wherever it sits), and every
// non-JSDoc BLOCK comment (e.g. `/* v8 ignore next 2 */`).
//
// The target path is REQUIRED as argv[2] and never defaulted: the packed-smoke
// verifier (scripts/effect-migration/p3-packed-install-smoke.ts) rewrites every
// `src/daemon/fleetd.bundle.mjs` literal in the recipe tail to a scratch copy,
// so this stage must operate on whatever path it is handed.
//
// `bun scripts/strip-bundle-jsdoc.ts --self-check` runs the lexer's targeted
// correctness assertions (string/template/regex `//` survival, protocol-relative
// comment text stripping, line-count preservation) without touching any file.

import { readFileSync, writeFileSync } from 'node:fs';

const NL = 10; // \n
const SLASH = 47; // /
const STAR = 42; // *
const BACKSLASH = 92; // \
const SINGLE = 39; // '
const DOUBLE = 34; // "
const BACKTICK = 96; // `
const DOLLAR = 36; // $
const LBRACE = 123; // {
const RBRACE = 125; // }
const LBRACKET = 91; // [
const RBRACKET = 93; // ]
const RPAREN = 41; // )
const SPACE = 32;
const TAB = 9;
const CR = 13;
const HASH = 35; // #
const BANG = 33; // !

// A column-0 esbuild file header: `// ` then a single space-free path token that
// ends in a source extension. The GENERATED banner has interior spaces after
// `// `, so `[^ ]+` never matches it — the banner is preserved.
const HEADER_RE = /^\/\/ [^ ]+\.(?:js|jsx|ts|tsx|mjs|cjs)$/;

// The two-line GENERATED banner's first line. A `//` line comment whose text
// begins with this is preserved verbatim even under full line-comment stripping,
// so the artifact's `#!/usr/bin/env bun` + banner head survives (asserted by the
// self-audit below and by the daemon-bundle-policy gate).
const BANNER_PREFIX = "// GENERATED by 'bun run bundle'";

// Keywords after which a `/` opens a regex literal, not a division.
const KEYWORDS_BEFORE_REGEX = new Set([
  'return',
  'typeof',
  'instanceof',
  'in',
  'of',
  'new',
  'delete',
  'void',
  'throw',
  'case',
  'do',
  'else',
  'yield',
  'await',
]);

const DIAGNOSTIC_NAMES = [
  '"DaemonHostControl"',
  '"LifecycleCoordinator"',
  '"BunProcessDriver"',
  '"makeDaemonApp"',
] as const;

export interface TransformOptions {
  readonly stripJsdoc: boolean;
  readonly stripHeaders: boolean;
  readonly stripLineComments: boolean;
}

export interface TransformResult {
  readonly code: string;
  readonly jsdocBlocks: number;
  readonly jsdocLines: number;
  readonly headerLines: number;
  readonly lineComments: number;
}

type TokenKind = 'block' | 'line' | 'regex' | 'div' | 'string' | 'template' | 'ident' | 'other';

interface Token {
  readonly end: number; // index just past the token
  readonly regexOk: boolean; // may a `/` immediately after this token open a regex?
  readonly kind: TokenKind;
}

function isIdentStart(code: number): boolean {
  return (
    (code >= 65 && code <= 90) || // A-Z
    (code >= 97 && code <= 122) || // a-z
    code === 95 || // _
    code === DOLLAR ||
    code > 127 // non-ASCII identifier characters
  );
}

function isIdentPart(code: number): boolean {
  return isIdentStart(code) || (code >= 48 && code <= 57); // 0-9
}

function isRegexFlag(code: number): boolean {
  return (code >= 97 && code <= 122) || (code >= 65 && code <= 90);
}

function isWhitespace(code: number): boolean {
  return code === SPACE || code === TAB || code === NL || code === CR;
}

// Same-line whitespace only: a space, tab, or CR, but never a newline. Used to
// retract the indentation/gap emitted immediately before a stripped `//` comment.
function isSpaceTabCr(code: number): boolean {
  return code === SPACE || code === TAB || code === CR;
}

/**
 * Strip JSDoc block comments, esbuild path headers, and/or every `//` line
 * comment from generated ESM.
 *
 * The whole file is walked with a single-pass lexer so that `/**` sequences and
 * `//` runs that live inside strings, template literals, or regexes are never
 * mistaken for comments. Strings/templates/regexes are always re-emitted
 * byte-for-byte; only genuine code-context comments are rewritten. Every rewrite
 * preserves the artifact's total line count: comment-only lines become empty
 * lines and trailing comments are dropped without pulling the next line up.
 */
export function transform(src: string, opts: TransformOptions): TransformResult {
  const n = src.length;
  const out: string[] = [];
  let i = 0;
  let regexOk = true; // does a `/` here open a regex literal?
  let jsdocBlocks = 0;
  let jsdocLines = 0;
  let headerLines = 0;
  let lineComments = 0;

  const cc = (k: number): number => src.charCodeAt(k); // NaN when out of range

  // Find the index just past a `*/` starting at a `/*`.
  function scanBlockEnd(start: number): number {
    let j = start + 2;
    while (j < n && !(cc(j) === STAR && cc(j + 1) === SLASH)) j += 1;
    return j < n ? j + 2 : n;
  }

  // Find the index of the terminating newline (or EOF) of a `//` comment.
  function scanLineEnd(start: number): number {
    let j = start + 2;
    while (j < n && cc(j) !== NL) j += 1;
    return j;
  }

  // Find the index just past the closing quote of a string literal. Bounded to
  // the current line — a raw newline in a single/double-quoted string is invalid
  // JS, so stopping there prevents a malformed input from swallowing the file.
  function scanString(start: number, quote: number): number {
    let j = start + 1;
    while (j < n) {
      const d = cc(j);
      if (d === BACKSLASH) {
        j += 2;
        continue;
      }
      if (d === quote) return j + 1;
      if (d === NL) return j;
      j += 1;
    }
    return j;
  }

  // Find the index just past the matching `}` of a `${ … }` interpolation, given
  // the index right after `${`. Tokenizes the expression with the same `classify`
  // used at top level so nested strings, templates, comments, AND regex literals
  // (e.g. `${e.replace(/'/g, "…")}`) never miscount braces or leak state.
  function scanInterpolation(start: number): number {
    let j = start;
    let depth = 0;
    let regexOk = true; // just after `${` an expression is expected
    while (j < n) {
      const c = cc(j);
      if (isWhitespace(c)) {
        j += 1;
        continue;
      }
      if (c === RBRACE && depth === 0) return j + 1;
      if (c === LBRACE) depth += 1;
      else if (c === RBRACE) depth -= 1;
      const token = classify(j, regexOk);
      if (token.kind !== 'block' && token.kind !== 'line') regexOk = token.regexOk;
      j = token.end;
    }
    return j;
  }

  // Find the index just past the closing backtick of a template literal.
  function scanTemplate(start: number): number {
    let j = start + 1;
    while (j < n) {
      const d = cc(j);
      if (d === BACKSLASH) {
        j += 2;
        continue;
      }
      if (d === BACKTICK) return j + 1;
      if (d === DOLLAR && cc(j + 1) === LBRACE) {
        j = scanInterpolation(j + 2);
        continue;
      }
      j += 1;
    }
    return j;
  }

  // Find the index just past the trailing flags of a regex literal.
  function scanRegex(start: number): number {
    let j = start + 1;
    let inClass = false;
    while (j < n) {
      const d = cc(j);
      if (d === BACKSLASH) {
        j += 2;
        continue;
      }
      if (d === NL) break; // unterminated regex — bounded to its line
      if (d === LBRACKET) inClass = true;
      else if (d === RBRACKET) inClass = false;
      else if (d === SLASH && !inClass) {
        j += 1;
        break;
      }
      j += 1;
    }
    while (j < n && isRegexFlag(cc(j))) j += 1;
    return j;
  }

  // Classify the single token starting at `j` (which must not be whitespace),
  // given whether a `/` here would open a regex. This is the one source of truth
  // for tokenization, shared by the top-level walk and `scanInterpolation`. For
  // comments `regexOk` is returned unchanged (they are transparent).
  function classify(j: number, regexOk: boolean): Token {
    const c = cc(j);
    if (c === SLASH) {
      const next = cc(j + 1);
      if (next === STAR) return { end: scanBlockEnd(j), regexOk, kind: 'block' };
      if (next === SLASH) return { end: scanLineEnd(j), regexOk, kind: 'line' };
      if (regexOk) return { end: scanRegex(j), regexOk: false, kind: 'regex' };
      return { end: j + 1, regexOk: true, kind: 'div' };
    }
    if (c === SINGLE || c === DOUBLE) {
      return { end: scanString(j, c), regexOk: false, kind: 'string' };
    }
    if (c === BACKTICK) {
      return { end: scanTemplate(j), regexOk: false, kind: 'template' };
    }
    if (isIdentStart(c)) {
      let k = j + 1;
      while (k < n && isIdentPart(cc(k))) k += 1;
      return { end: k, regexOk: KEYWORDS_BEFORE_REGEX.has(src.slice(j, k)), kind: 'ident' };
    }
    // Any other single character (operators, punctuation, digits, braces). A `/`
    // after `)` or `]` is division; after anything else (incl. `{`/`}`) a regex.
    return { end: j + 1, regexOk: !(c === RPAREN || c === RBRACKET), kind: 'other' };
  }

  // Preserve the shebang line verbatim, if present.
  if (cc(0) === HASH && cc(1) === BANG) {
    const nl = src.indexOf('\n');
    const end = nl === -1 ? n : nl + 1;
    out.push(src.slice(0, end));
    i = end;
  }

  while (i < n) {
    const c = cc(i);

    // Whitespace run — transparent to regex/division disambiguation.
    if (isWhitespace(c)) {
      let j = i + 1;
      while (j < n && isWhitespace(cc(j))) j += 1;
      out.push(src.slice(i, j));
      i = j;
      continue;
    }

    const token = classify(i, regexOk);

    if (token.kind === 'block') {
      // Strip JSDoc (`/**`), keep every other block comment. Comments are
      // transparent to regexOk, so it is left unchanged.
      if (opts.stripJsdoc && cc(i + 2) === STAR) {
        const commentBody = src.slice(i, token.end);
        let lines = 0;
        for (let k = 0; k < commentBody.length; k += 1) {
          if (commentBody.charCodeAt(k) === NL) lines += 1;
        }
        out.push(lines > 0 ? '\n'.repeat(lines) : '');
        jsdocBlocks += 1;
        jsdocLines += lines;
      } else {
        out.push(src.slice(i, token.end));
      }
    } else if (token.kind === 'line') {
      const comment = src.slice(i, token.end);
      const atCol0 = i === 0 || cc(i - 1) === NL;
      if (comment.startsWith(BANNER_PREFIX)) {
        // The GENERATED banner is preserved verbatim under every lever.
        out.push(comment);
      } else if (opts.stripHeaders && atCol0 && HEADER_RE.test(comment)) {
        // Blank a column-0 esbuild path header (a no-op subset of the line-comment
        // lever, kept separate only so its count stays attributable).
        out.push('');
        headerLines += 1;
      } else if (opts.stripLineComments) {
        // Drop the comment text. The comment token never includes its terminating
        // newline, so removing it cannot join lines. Retract any same-line
        // whitespace already emitted just before the `//` (the trailing tab/space
        // run of the previous chunk, never a preceding newline): a comment-only
        // line collapses to a truly empty line and a trailing comment leaves no
        // dangling space.
        const last = out.length > 0 ? (out[out.length - 1] ?? '') : '';
        let k = last.length;
        while (k > 0 && isSpaceTabCr(last.charCodeAt(k - 1))) k -= 1;
        if (k < last.length) out[out.length - 1] = last.slice(0, k);
        out.push('');
        lineComments += 1;
      } else {
        out.push(comment);
      }
    } else {
      out.push(src.slice(i, token.end));
      regexOk = token.regexOk;
    }

    i = token.end;
  }

  return { code: out.join(''), jsdocBlocks, jsdocLines, headerLines, lineComments };
}

const ALL_STRIP: TransformOptions = {
  stripJsdoc: true,
  stripHeaders: true,
  stripLineComments: true,
};

function main(): void {
  const target = process.argv[2];
  if (target === undefined || target.length === 0) {
    throw new Error('strip-bundle-jsdoc: target bundle path is required as argv[2]');
  }

  const original = readFileSync(target, 'utf8');
  const result = transform(original, ALL_STRIP);
  const { code } = result;

  // ── Self-audit — abort the build if any invariant is violated ──────────────
  const inLines = original.split('\n').length;
  const outLines = code.split('\n').length;
  if (outLines !== inLines) {
    throw new Error(`strip-bundle-jsdoc: line count changed ${inLines} -> ${outLines}`);
  }
  for (const name of DIAGNOSTIC_NAMES) {
    if (!code.includes(name)) {
      throw new Error(`strip-bundle-jsdoc: diagnostic name ${name} did not survive`);
    }
  }
  const head = code.split('\n', 3);
  if (head[0] === undefined || !head[0].startsWith('#!/usr/bin/env bun')) {
    throw new Error('strip-bundle-jsdoc: shebang missing after transform');
  }
  if (head[1] === undefined || !head[1].startsWith("// GENERATED by 'bun run bundle'")) {
    throw new Error('strip-bundle-jsdoc: GENERATED banner missing after transform');
  }
  const second = transform(code, ALL_STRIP);
  if (second.code !== code) {
    throw new Error('strip-bundle-jsdoc: transform is not idempotent');
  }

  writeFileSync(target, code);

  const savedBytes = Buffer.byteLength(original, 'utf8') - Buffer.byteLength(code, 'utf8');
  process.stdout.write(
    `strip-bundle-jsdoc: stripped ${result.jsdocBlocks} JSDoc blocks ` +
      `(${result.jsdocLines} lines) + ${result.headerLines} file headers + ` +
      `${result.lineComments} line comments, ` +
      `saved ${savedBytes} raw bytes, line count ${outLines} preserved\n`,
  );
}

// ── Self-check ───────────────────────────────────────────────────────────────
// Targeted lexer proofs that run without touching any file. The exhaustive
// correctness gate is the esbuild-minify equivalence check in the build recipe's
// verifier; these cases document and lock the specific hazards by hand.
function selfCheck(): void {
  const strip = (input: string): string => transform(input, ALL_STRIP).code;
  let passed = 0;
  const check = (label: string, input: string, expected: string): void => {
    const actual = strip(input);
    if (actual !== expected) {
      throw new Error(
        `strip-bundle-jsdoc self-check FAILED: ${label}\n` +
          `  input:    ${JSON.stringify(input)}\n` +
          `  expected: ${JSON.stringify(expected)}\n` +
          `  actual:   ${JSON.stringify(actual)}`,
      );
    }
    // Every transform must preserve line count and be idempotent.
    if (actual.split('\n').length !== input.split('\n').length) {
      throw new Error(`strip-bundle-jsdoc self-check FAILED: ${label} changed line count`);
    }
    if (strip(actual) !== actual) {
      throw new Error(`strip-bundle-jsdoc self-check FAILED: ${label} is not idempotent`);
    }
    passed += 1;
  };

  // `//` inside string/template/regex literals must SURVIVE untouched.
  check('single-quoted url', "const u = 'http://x';", "const u = 'http://x';");
  check('double-quoted url', 'const u = "a//b";', 'const u = "a//b";');
  check('template url', 'const u = `x//y`;', 'const u = `x//y`;');
  check(
    'template with nested regex interpolation',
    'const u = `${e.replace(/[\'/]/g, "z")}//tail`;',
    'const u = `${e.replace(/[\'/]/g, "z")}//tail`;',
  );
  check('regex literal after paren', 'if (/a\\/\\/b/.test(x)) {}', 'if (/a\\/\\/b/.test(x)) {}');
  check('regex after return', 'return /x\\/y/;', 'return /x\\/y/;');
  check('division is not a regex', 'a = b / c / d;', 'a = b / c / d;');

  // Genuine comments must be STRIPPED; protocol-relative text in a comment is
  // just comment text and goes with it.
  check('trailing comment removed', 'foo();  // note', 'foo();');
  check('protocol-relative in comment', 'x;  // see //example.com/p', 'x;');
  check(
    'string survives while adjacent comment strips',
    "const u = 'http://x';  // gone",
    "const u = 'http://x';",
  );
  check('comment-only line collapses to empty', '  // solo', '');
  check('col-0 comment collapses to empty', '// solo', '');

  // Trailing comment dropped WITHOUT joining the next line.
  check('no line join', 'a();  // c\nb();', 'a();\nb();');
  check('comment-only line keeps blank slot', 'a();\n  // c\nb();', 'a();\n\nb();');

  // The banner is preserved verbatim under full stripping; a normal col-0
  // comment on the next line is not.
  check(
    'banner preserved, following comment stripped',
    `${BANNER_PREFIX} — do not edit.\n// junk`,
    `${BANNER_PREFIX} — do not edit.\n`,
  );

  // Block comments: JSDoc goes (line-preserving), other blocks stay.
  check('jsdoc block blanked to newlines', '/**\n * d\n */\nx;', '\n\n\nx;');
  check('non-jsdoc block kept', '/* v8 ignore next */\nx;', '/* v8 ignore next */\nx;');

  // Shebang is preserved and a following comment still strips.
  check('shebang preserved', '#!/usr/bin/env bun\n// header\nx;', '#!/usr/bin/env bun\n\nx;');

  process.stdout.write(`strip-bundle-jsdoc self-check: ${String(passed)} cases passed\n`);
}

if (import.meta.main) {
  if (process.argv[2] === '--self-check') selfCheck();
  else main();
}
